---
ID: "87116d24-3ecd-4d80-aaff-fc66f8029d98"
Parent: "21e80e70-fd26-4b2a-9a70-357071dbaeed"
Template: "979fdf53-37cb-434c-bbff-f7aaf6abaac0"
Path: "/sitecore/content/fwd/fwd-th/Components/Forms/Application/Insurance application form"
DB: master
SharedFields:
- ID: "6cd9b2c8-a41a-439e-8166-b0b7b0086f49"
  Hint: buttonMode
  Value: "{02A5A5C7-C318-4919-B773-86A65BA98969}"
- ID: "ff451472-1b55-4228-b14d-ab9b2a449792"
  Hint: isPageSearchable
  Type: Checkbox
  Value: 1
- ID: "ff4d8f7a-06bf-45ab-8306-c9bf727c5bd9"
  Hint: buttonIcon
  Value: "{A03E086C-A7FD-4FD0-8D38-AA313D696179}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200514T105520Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\fwdtestauthor
    - ID: "74eb711f-f1e9-4622-a04d-94f5ae11ef15"
      Hint: description
      Value:  
    - ID: "c9430c02-23e5-4887-87e5-872059655027"
      Hint: topics
      Value: "{6B9F4DF7-E190-405B-8F15-225FA092BA3B}"
    - ID: "d57a04ff-b168-4c1e-8221-799439725666"
      Hint: title
      Value: Insurance application form
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link linktype="media" target="" id="{023EE9D3-8B2B-4306-B4ED-6D9C8E0AD3B8}" />
    - ID: "f55ccf38-f0bf-4b15-b4e9-edb6e07245b4"
      Hint: contentType
      Value: "{04E7400A-22DE-4392-A4AD-B78B7AA3B7A3}"
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200514T105654Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\fwdtestauthor
    - ID: "74eb711f-f1e9-4622-a04d-94f5ae11ef15"
      Hint: description
      Value:  
    - ID: "c9430c02-23e5-4887-87e5-872059655027"
      Hint: topics
      Value: "{6B9F4DF7-E190-405B-8F15-225FA092BA3B}"
    - ID: "d57a04ff-b168-4c1e-8221-799439725666"
      Hint: title
      Value: ใบคำร้องขอเอาประกันชีวิต แบบมีคำถามสุขภาพ
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ใบคำร้องขอเอาประกันชีวิต แบบมีคำถามสุขภาพ" linktype="media" target="" id="{33F6D7D2-65BF-4B27-AA46-015BC8945365}" />
    - ID: "f55ccf38-f0bf-4b15-b4e9-edb6e07245b4"
      Hint: contentType
      Value: "{04E7400A-22DE-4392-A4AD-B78B7AA3B7A3}"
