---
ID: "18fc20f3-259e-44a0-b9da-f3e117cf1f96"
Parent: "d796d1a1-7819-4ee0-82f4-a3e0b561ab80"
Template: "175e0994-9695-4a52-9837-b6e9f53d9d56"
Path: "/sitecore/content/fwd/fwd-th/Home/Products/Health/the-exclusive-care/local-folder/product-plan-list"
DB: master
SharedFields:
- ID: "31ed2cdd-191f-4c8e-94fe-71b04431ef3b"
  Hint: planCards
  Type: Multilist
  Value: |
    {E97255DA-5B4E-4A07-A9C2-2290225D41B0}
    {4258DFBA-3090-4719-94CF-A6275A09ED5A}
    {D3FFFF4D-1B1E-4394-A732-9FDA12630428}
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Plan List
  Versions:
  - Version: 1
    Fields:
    - ID: "048c3952-ef2e-455f-9a0d-4d9e9073bea9"
      Hint: calculateLink
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191213T070944Z
    - ID: "40610ec3-80f6-4071-92c3-3df8c6dc0a93"
      Hint: title
      Value: "Interested?"
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: 
    - ID: "f55de024-97c9-4db0-abf7-23bc3e35a96e"
      Hint: subTitle
      Value: "Take a closer look at all the details - and compare this with some of our other products."
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "048c3952-ef2e-455f-9a0d-4d9e9073bea9"
      Hint: calculateLink
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T055202Z
    - ID: "40610ec3-80f6-4071-92c3-3df8c6dc0a93"
      Hint: title
      Value: "สนใจ?"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: 
    - ID: "f55de024-97c9-4db0-abf7-23bc3e35a96e"
      Hint: subTitle
      Value: ลองดูรายละเอียดทั้งหมด และเปรียบเทียบกับผลิตภัณฑ์อื่นๆ ของเรา
