---
ID: "0cdb0e78-402e-412d-a75f-0b486a7cbbe8"
Parent: "d0459c20-e8b4-466e-ae96-ebc506a79797"
Template: "8d254d4a-bd30-4b07-8fa0-7464260d4bbc"
Path: "/sitecore/content/fwd/fwd-th/Content/Tags/supportTags/product-type"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Type
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191101T165304Z
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200211T064953Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
