---
ID: "99fbf725-9637-4c12-ad92-2a1cc908d5cb"
Parent: "834f9560-60ee-4787-84b5-49616d54f8d7"
Template: "175e0994-9695-4a52-9837-b6e9f53d9d56"
Path: "/sitecore/content/fwd/fwd-th/Home/Products/Health/opd-plus/local-folder/product-plan-list"
DB: master
SharedFields:
- ID: "31ed2cdd-191f-4c8e-94fe-71b04431ef3b"
  Hint: planCards
  Type: Multilist
  Value: |
    {0CB60CC2-5CDC-4F48-8517-0E26599E9FC4}
    {46AACC07-BA38-4083-A3EF-E7412664ABD5}
    {AB7CD32D-F01F-4AD1-9A53-5BC88BAB8644}
    {C08D5139-A403-4D45-A972-558BD7A019EF}
    {CE5C2D3F-B1F3-4E0F-AD08-1F0943782D5E}
    {FBC2FE88-7B7E-4FB9-B362-C667B79D9BB1}
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{BD9D2AB7-4AC1-454B-A6A8-53B1DC5C0AC4}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Plan List
  Versions:
  - Version: 1
    Fields:
    - ID: "048c3952-ef2e-455f-9a0d-4d9e9073bea9"
      Hint: calculateLink
      Value: |
        <link text="Calculate" linktype="form" querystring="" target="" id="{1B3EEC51-98F0-4820-953C-AE3DC6BB8FB3}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191213T070944Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "40610ec3-80f6-4071-92c3-3df8c6dc0a93"
      Hint: title
      Value: "Interested?"
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: 
    - ID: "f55de024-97c9-4db0-abf7-23bc3e35a96e"
      Hint: subTitle
      Value: "Take a closer look at all the details - and compare this with some of our other products."
  - Version: 2
    Fields:
    - ID: "048c3952-ef2e-455f-9a0d-4d9e9073bea9"
      Hint: calculateLink
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200713T065201Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "40610ec3-80f6-4071-92c3-3df8c6dc0a93"
      Hint: title
      Value: "Interested?"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Hein
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200713T065201Z
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: 
    - ID: "f55de024-97c9-4db0-abf7-23bc3e35a96e"
      Hint: subTitle
      Value: "Take a closer look at all the details - and compare this with some of our other products."
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "048c3952-ef2e-455f-9a0d-4d9e9073bea9"
      Hint: calculateLink
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T055202Z
    - ID: "40610ec3-80f6-4071-92c3-3df8c6dc0a93"
      Hint: title
      Value: "สนใจ?"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: 
    - ID: "f55de024-97c9-4db0-abf7-23bc3e35a96e"
      Hint: subTitle
      Value: ลองดูรายละเอียดทั้งหมด และเปรียบเทียบกับผลิตภัณฑ์อื่นๆ ของเรา
