---
ID: "09b9fced-7b68-4fec-82eb-64f520633f92"
Parent: "d113f6de-3abe-46b4-bb31-11cc301c293e"
Template: "69b601a8-8555-4411-8c17-aa91671eec32"
Path: /sitecore/templates/Branches/FWD/Foundation/Market Site Rollout/MultiMarketSiteRoot/$name/Content/Tags/productsTags/planComponent/Package
DB: master
SharedFields:
- ID: "a903eb23-a8d6-4a9a-bd27-4bd363b1fcf0"
  Hint: searchName
  Value: Package
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03834b49-81cd-4ea6-956b-1cf3018dcf8a"
      Hint: name
      Value: Package
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191101T173947Z
