---
ID: "58159eb4-171a-4cc2-9f53-ec130ea31d76"
Parent: "1dbb9b41-1f0b-46fc-9d00-23566f2fbe56"
Template: "f0760974-f5ae-4730-8610-a8304e1d4155"
Path: "/sitecore/content/fwd/fwd-th/Home/group-insurance/local-folder/card-list/Mobile application"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 75
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0389d126-0f13-4dbc-9bfa-6d4126a8a3ed"
      Hint: description
      Value: You and your employees can access our healthcare app &ndash; making it quicker and easier to check coverage and manage details.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200130T110516Z
    - ID: "37089077-fd76-4e9d-836f-21c3bcbe2db9"
      Hint: title
      Value: Use the FWD healthcare app
    - ID: "967df5d0-46c0-4127-a3ea-860b801cd2ee"
      Hint: subtitle
      Value: You and your employees will have access to our healthcare mobile app – making it quicker and easier to check your coverage and manage your details.
    - ID: "b89c3acb-0850-4829-b257-433050c4b6ba"
      Hint: mobileImage
      Value: |
        <image mediaid="{FA40F06D-6858-45CA-89FE-48F9703DE03C}" />
    - ID: "d10b1d70-37ae-45da-91b5-2ea4484420b9"
      Hint: image
      Value: |
        <image mediaid="{FA40F06D-6858-45CA-89FE-48F9703DE03C}" cropx="0.50" cropy="0.48" focusx="-0.004405286343612369" focusy="0.046875" />
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "0389d126-0f13-4dbc-9bfa-6d4126a8a3ed"
      Hint: description
      Value: ทั้งผู้บริหารและพนักงานสามารถตรวจสอบความคุ้มครองและจัดการรายละเอียดของกรมธรรม์ประกันสุขภาพผ่านโมบาย แอปพลิเคชั่น ได้อย่างรวดเร็วและง่ายดาย
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200217T102423Z
    - ID: "37089077-fd76-4e9d-836f-21c3bcbe2db9"
      Hint: title
      Value: แอปพลิเคชัน FWD  Healthcare
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "967df5d0-46c0-4127-a3ea-860b801cd2ee"
      Hint: subtitle
      Value: 
    - ID: "b89c3acb-0850-4829-b257-433050c4b6ba"
      Hint: mobileImage
      Value: |
        <image mediaid="{FA40F06D-6858-45CA-89FE-48F9703DE03C}" />
    - ID: "d10b1d70-37ae-45da-91b5-2ea4484420b9"
      Hint: image
      Value: |
        <image mediaid="{FA40F06D-6858-45CA-89FE-48F9703DE03C}" cropx="0.50" cropy="0.48" focusx="-0.004405286343612369" focusy="0.046875" />
