---
ID: "5ac59796-bab3-4b0c-8e01-dc0e8014afed"
Parent: "1946aa80-cdb2-477e-9f76-198d7c70c2d6"
Template: "f0760974-f5ae-4730-8610-a8304e1d4155"
Path: "/sitecore/content/fwd/fwd-th/Home/GroupLandingPage/local-folder/card-list/Mobile application"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0389d126-0f13-4dbc-9bfa-6d4126a8a3ed"
      Hint: description
      Value: "Get a real-time support round the clock for all enquiries."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200130T110516Z
    - ID: "37089077-fd76-4e9d-836f-21c3bcbe2db9"
      Hint: title
      Value: Mobile application
    - ID: "967df5d0-46c0-4127-a3ea-860b801cd2ee"
      Hint: subtitle
      Value: "Get a real-time support round the clock for all enquiries."
    - ID: "d10b1d70-37ae-45da-91b5-2ea4484420b9"
      Hint: image
      Value: |
        <image mediaid="{3F04B594-97C9-4C3C-B4D6-5710B95B72DA}" cropx="0.50" cropy="0.48" focusx="-0.004405286343612369" focusy="0.046875" />
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "0389d126-0f13-4dbc-9bfa-6d4126a8a3ed"
      Hint: description
      Value: "Get a real-time support round the clock for all enquiries."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200217T102423Z
    - ID: "37089077-fd76-4e9d-836f-21c3bcbe2db9"
      Hint: title
      Value: Mobile application
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "967df5d0-46c0-4127-a3ea-860b801cd2ee"
      Hint: subtitle
      Value: "Get a real-time support round the clock for all enquiries."
    - ID: "d10b1d70-37ae-45da-91b5-2ea4484420b9"
      Hint: image
      Value: |
        <image mediaid="{3F04B594-97C9-4C3C-B4D6-5710B95B72DA}" cropx="0.50" cropy="0.48" focusx="-0.004405286343612369" focusy="0.046875" />
