---
ID: "a57b5556-98b3-4112-ac9f-1926d90455b8"
Parent: "a64b49ed-0ac3-4c5f-9d21-85c73fc5c566"
Template: "69b601a8-8555-4411-8c17-aa91671eec32"
Path: "/sitecore/content/fwd/fwd-th/Content/Tags/commonTags/contentType/Product"
DB: master
SharedFields:
- ID: "a903eb23-a8d6-4a9a-bd27-4bd363b1fcf0"
  Hint: searchName
  Value: Product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03834b49-81cd-4ea6-956b-1cf3018dcf8a"
      Hint: name
      Value: Product
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191101T172906Z
- Language: th
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "03834b49-81cd-4ea6-956b-1cf3018dcf8a"
      Hint: name
      Value: Product
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200110T060406Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
  - Version: 2
    Fields:
    - ID: "03834b49-81cd-4ea6-956b-1cf3018dcf8a"
      Hint: name
      Value: ผลิตภัณฑ์
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200211T064947Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200211T064947Z
