---
ID: "8319a071-f46d-422f-a0c5-b1d002e5c6ae"
Parent: "e5edfaa8-44dd-4e9b-a8c0-ae6be9fb5d88"
Template: "69b601a8-8555-4411-8c17-aa91671eec32"
Path: /sitecore/templates/Branches/FWD/Foundation/Market Site Rollout/MultiMarketSiteRoot/$name/Content/Tags/supportTags/supporttopic/Applications
DB: master
SharedFields:
- ID: "a903eb23-a8d6-4a9a-bd27-4bd363b1fcf0"
  Hint: searchName
  Value: Applications
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03834b49-81cd-4ea6-956b-1cf3018dcf8a"
      Hint: name
      Value: Applications
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191101T174326Z
