---
ID: "c4669917-2b47-429a-af02-c9989aff3c09"
Parent: "8cceff29-fdc1-4686-a225-3f8403ad2f19"
Template: "51555475-5028-4b05-9b45-53be53615704"
Path: "/sitecore/content/fwd/fwd-th/Home/Products/Accident/prakan-kon-kla-MAX/local-folder/Product brochure"
DB: master
SharedFields:
- ID: "6cd9b2c8-a41a-439e-8166-b0b7b0086f49"
  Hint: buttonMode
  Value: "{2D7E3979-8DAE-42D1-BFDF-45522DB9A1B9}"
- ID: "9cb76228-fc26-48b7-bd66-1c6e133b625d"
  Hint: secondaryLinkButtonMode
  Value: 
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{BD9D2AB7-4AC1-454B-A6A8-53B1DC5C0AC4}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 525
- ID: "dab4200c-a87f-4605-b2f7-2544616ece6e"
  Hint: secondaryLinkButtonIcon
  Value: 
- ID: "ff4d8f7a-06bf-45ab-8306-c9bf727c5bd9"
  Hint: buttonIcon
  Value: "{96BC3A53-AB72-49EF-BA31-37D901B59263}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product brochure
  Versions:
  - Version: 1
    Fields:
    - ID: "080cac52-a76d-44ce-a9e6-6d60dc56ad03"
      Hint: subTitle
      Value: 
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191108T094556Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: Get our official product brochure for personal use or share it with friends and family.
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: Product brochure
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="Download brochure" linktype="media" target="" id="{3D6658D8-A0BF-4E75-B3E2-D050FABCF4E1}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
  - Version: 2
    Fields:
    - ID: "080cac52-a76d-44ce-a9e6-6d60dc56ad03"
      Hint: subTitle
      Value: 
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200825T134222Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: Get our official product brochure for personal use or share it with friends and family.
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\contentauthor
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200825T134222Z
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: Product brochure
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="Download brochure" linktype="media" target="" id="{3D6658D8-A0BF-4E75-B3E2-D050FABCF4E1}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
- Language: th
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product brochure
  Versions:
  - Version: 1
    Fields:
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T055157Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "d0be2ac7-85f9-4ba4-91da-613370dbd6d6"
      Hint: secondaryLink
      Value: 
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{0472860A-7341-46B7-AB43-412164DB4231}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
  - Version: 2
    Fields:
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200820T061646Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\parid
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200820T061646Z
    - ID: "d0be2ac7-85f9-4ba4-91da-613370dbd6d6"
      Hint: secondaryLink
      Value: 
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{0472860A-7341-46B7-AB43-412164DB4231}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
  - Version: 3
    Fields:
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200825T134313Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\contentauthor
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200825T134313Z
    - ID: "d0be2ac7-85f9-4ba4-91da-613370dbd6d6"
      Hint: secondaryLink
      Value: 
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{0472860A-7341-46B7-AB43-412164DB4231}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
  - Version: 4
    Fields:
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200930T102840Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Hein
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200930T102840Z
    - ID: "d0be2ac7-85f9-4ba4-91da-613370dbd6d6"
      Hint: secondaryLink
      Value: 
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{4A260EE7-AF90-4F80-BF36-2E4CD7B9C8EC}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
  - Version: 5
    Fields:
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201006T083908Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Hein
    - ID: "b4f00351-1ba4-4f74-9101-d9c75b5b91de"
      Hint: videoYouTubeID
      Value: 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20201006T083908Z
    - ID: "d0be2ac7-85f9-4ba4-91da-613370dbd6d6"
      Hint: secondaryLink
      Value: 
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{C9A3BE90-01D6-4E9F-9B93-D8375E6B97CF}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
