---
ID: "19f7506a-7825-471f-8b85-a5666c8f319f"
Parent: "8f670344-315a-4d39-b9c8-06bbc7d89188"
Template: "471e5ba2-0ea8-4fe6-9a4f-ea4333b2b57a"
Path: /sitecore/templates/Branches/FWD/Foundation/Market Site Rollout/MultiMarketSiteRoot/$name/Content/Forms/tasks/makeAnEnquiry
DB: master
SharedFields:
- ID: "0bb8c93b-a99d-46b3-8e18-fa27970a244c"
  Hint: key
  Value: 2
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Make a general enquiry
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200203T041243Z
    - ID: "b95c8194-e837-46c4-ab8a-a5c6874359cf"
      Hint: value
      Value: Make a general enquiry
- Language: th
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: สอบถามข้อมูลทั่วไป
  Versions:
