---
ID: "888f0a09-9dd4-423e-89d6-d47402345b0a"
Parent: "131f2aba-62ad-4e77-bc04-a3482760ef74"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/FWD/Feature/Global/PowerShell/_powerShellModulesSetting/Settings/settings
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: /sitecore/templates/FWD/Project/Global/Configuration/Repository Folder
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: NameLookupValueListEx
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Settings
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200516T093454Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
