---
ID: "1fa80022-9f46-473b-a35b-0450fa491831"
Parent: "a09f0b08-17c3-43ba-a3b1-fd62ba1e29c9"
Template: "40da990f-39dd-4d66-a9be-849f4ecffd22"
Path: "/sitecore/content/fwd/fwd-th/Home/Support/loan-application"
DB: master
SharedFields:
- ID: "5a8b95c0-14d6-4531-bd75-61b658cbfa25"
  Hint: contentType
  Value: "{04E7400A-22DE-4392-A4AD-B78B7AA3B7A3}"
- ID: "73b480d6-f70d-487d-a830-89e07a922ebd"
  Hint: pageType
  Value: "{FB2C4A8A-0593-44B7-B7C4-AE07AF4F8BB2}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{ABACA3EB-6579-47EF-B88F-C9E713F1EC17}"
          s:ds="{CCCFE6F7-1169-409A-AB37-3CAE30D24488}"
          s:par="paddingBottom=%7bDE1D2D2E-FDFA-4E0D-A649-E38F3822F767%7d&amp;anchorText&amp;backgroundColor=%7bCBDC6265-D09F-4982-981A-BCC8F118F36F%7d&amp;paddingTop=%7bDE1D2D2E-FDFA-4E0D-A649-E38F3822F767%7d&amp;enableMargin&amp;divider" />
        <r
          uid="{C879EB9D-195D-4984-B164-F1DD756158FA}"
          s:ds="{8F494431-8C05-46B2-9401-B2A8B7357098}"
          s:par="HeroBannerVariant=%7B0B1166D9-2C27-4392-B0FB-C3E5F2C18380%7D&amp;PlayVideoInBackground&amp;anchorText&amp;backgroundColor=%7BCBDC6265-D09F-4982-981A-BCC8F118F36F%7D&amp;paddingTop=%7B0EF687F9-57C6-4122-B17E-DFBCF0A0BAEA%7D&amp;paddingBottom=%7B0EF687F9-57C6-4122-B17E-DFBCF0A0BAEA%7D&amp;divider" />
        <r
          uid="{2476A374-8836-45FE-AF59-3CD0AE06BE82}">
          <p:d />
        </r>
        <r
          uid="{AF5E358C-881F-4832-A405-BAC921DF13DA}"
          p:after="r[@uid='{C879EB9D-195D-4984-B164-F1DD756158FA}']"
          s:ds="{C3337D94-C0B8-4C2E-8FB0-21686DEBB8DF}"
          s:id="{BF3FAD76-A9F0-45C5-A9E0-8F37D97B7E50}"
          s:par="imageAlignment&amp;showMediaOnMobile&amp;contentBlockType=%7BE096FFCB-C7BE-461F-843E-BA5BECF20BA8%7D&amp;IsMerge=1&amp;anchorText&amp;backgroundColor=%7B62070F56-8307-4B27-A4DB-E6F90EC9767B%7D&amp;paddingTop=%7B39A5175B-32BA-4968-842E-ABFC2410ABFF%7D&amp;paddingBottom=%7BDE1D2D2E-FDFA-4E0D-A649-E38F3822F767%7D&amp;divider"
          s:ph="jss-main" />
        <r
          uid="{5583DF9E-2A2C-4090-B058-5AB436E6F59F}"
          p:after="r[@uid='{AF5E358C-881F-4832-A405-BAC921DF13DA}']"
          s:ds="{1C6269A5-AEC3-4080-9213-0AE7CCF8535F}"
          s:id="{F0B75A00-90E8-4447-B01D-69F6564D9F5F}"
          s:par="anchorText&amp;backgroundColor=%7B62070F56-8307-4B27-A4DB-E6F90EC9767B%7D&amp;paddingTop=%7BDE1D2D2E-FDFA-4E0D-A649-E38F3822F767%7D&amp;paddingBottom=%7B39A5175B-32BA-4968-842E-ABFC2410ABFF%7D&amp;divider"
          s:ph="jss-main" />
        <r
          uid="{57AD34E9-D9E1-4B92-A392-E0A41486C935}"
          s:ds="{2089CF11-00FE-47BA-B97D-A438DF6BEF13}"
          s:par="buttonAlignment=%7B8570C16E-5CA9-4A85-8A62-C661A5B4350B%7D&amp;variant&amp;anchorText&amp;backgroundColor=%7BEBDF491B-A72E-47CA-A391-E44A39C9C329%7D&amp;paddingTop=%7B39A5175B-32BA-4968-842E-ABFC2410ABFF%7D&amp;paddingBottom=%7B39A5175B-32BA-4968-842E-ABFC2410ABFF%7D&amp;divider" />
        <r
          uid="{D6134FB5-960B-4784-8AE2-7231655F27DC}"
          s:ds="{882A58F8-DDD7-4BA9-8EFC-D8D561AEC4F1}"
          s:par="anchorText&amp;divider&amp;backgroundColor=%7bF6BA8583-13B7-4FC7-A1D4-FC8F11DCE6B1%7d&amp;paddingTop=%7b39A5175B-32BA-4968-842E-ABFC2410ABFF%7d&amp;paddingBottom=%7bDE1D2D2E-FDFA-4E0D-A649-E38F3822F767%7d" />
      </d>
    </r>
- ID: "ff451472-1b55-4228-b14d-ab9b2a449792"
  Hint: isPageSearchable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Loan application
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191118T125101Z
    - ID: "2742410f-6b3f-495d-88d4-598ab3d1f2b9"
      Hint: metadataDescription
      Value: Learn more about getting an FWD loan by visiting our website.
    - ID: "7d76900d-2ec8-4b47-81fc-2baf505287be"
      Hint: metadataTitle
      Value: FWD loan application
    - ID: "f73058c2-3f5c-485c-9e31-e71c53f184ac"
      Hint: metadataKeywords
      Value: 
- Language: th
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Loan application
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T085051Z
    - ID: "2742410f-6b3f-495d-88d4-598ab3d1f2b9"
      Hint: metadataDescription
      Value: ศึกษาเพิ่มเติมเกี่ยวกับการขอกู้เงินตามกรมธรรม์ได้ที่เว็บไซต์ของเรา 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "7d76900d-2ec8-4b47-81fc-2baf505287be"
      Hint: metadataTitle
      Value: การขอกู้เงินตามกรมธรรม์
    - ID: "f73058c2-3f5c-485c-9e31-e71c53f184ac"
      Hint: metadataKeywords
      Value: 
