---
ID: "2949ab35-de7a-4893-88e2-779f860cf97a"
Parent: "c2cbf05d-3eb4-49ff-b40f-f0308003ffac"
Template: "b4c08e6e-4910-4cf1-8357-5135729afafb"
Path: "/sitecore/content/fwd/fwd-th/Home/about-us/local-folder/product-link-1"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 185
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: A range of plans
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191018T093839Z
    - ID: "9466c25e-e97e-4373-91c3-e648a98ea63e"
      Hint: title
      Value: A range of plans and support for families and individuals
    - ID: "9aef0a70-2235-4e84-9854-1e4597e6c385"
      Hint: subTitle
      Value: From parenthood to retirement, while you’re navigating life’s big moments, we’ll support you with products that meet your needs.
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="FWD for individuals" anchor="" linktype="internal" class="" title="View our range of plans and coverage "  querystring="" id="{528D2C44-05E6-4E13-8C4C-0A7FFF35B120}" />
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200108T171617Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "9466c25e-e97e-4373-91c3-e648a98ea63e"
      Hint: title
      Value: แผนประกันที่หลากหลาย เพื่อให้คุณเลือกประกันที่ใช่ได้ง่ายยิ่งขึ้น
    - ID: "9aef0a70-2235-4e84-9854-1e4597e6c385"
      Hint: subTitle
      Value: ในขณะที่คุณกำลังก้าวผ่านช่วงเวลาที่ยิ่งใหญ่ของชีวิต ไม่ว่าจะเป็นการกลายเป็นพ่อแม่หรือการเกษียณจากงาน เราพร้อมเคียงข้างดูแลด้วยแผนประกันชีวิตที่ตรงกับความต้องการของคุณ
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="เอฟดับบลิวดี ประกันรายบุคคล" anchor="" linktype="internal" class="" title="ดูแผนการประกันและความคุ้มครองที่หลากหลาย"  querystring="" id="{528D2C44-05E6-4E13-8C4C-0A7FFF35B120}" />
