---
ID: "649cc5f7-333a-4a86-9ceb-1c659af19ccb"
Parent: "c2cbf05d-3eb4-49ff-b40f-f0308003ffac"
Template: "b4c08e6e-4910-4cf1-8357-5135729afafb"
Path: "/sitecore/content/fwd/fwd-th/Home/about-us/local-folder/product-link-2"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 187
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Flexible and adjustable 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191018T093744Z
    - ID: "9466c25e-e97e-4373-91c3-e648a98ea63e"
      Hint: title
      Value: Flexible and adjustable group insurance 
    - ID: "9aef0a70-2235-4e84-9854-1e4597e6c385"
      Hint: subTitle
      Value: Our group insurance is designed to be customised. Because we know that each business is different.
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="FWD for business" anchor="" linktype="internal" class="" title="View our group insurance plans for businesses"  querystring="" id="{0D08A74E-81B5-4DFD-9B53-B8AD7413F555}" />
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200108T171627Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "9466c25e-e97e-4373-91c3-e648a98ea63e"
      Hint: title
      Value: ประกันชีวิตกลุ่มที่ยืดหยุ่นและปรับเปลี่ยนได้
    - ID: "9aef0a70-2235-4e84-9854-1e4597e6c385"
      Hint: subTitle
      Value: ประกันชีวิตกลุ่มของเราถูกออกแบบมาให้ปรับเปลี่ยนให้ตรงกับความต้องการ เพราะเรารู้ดีว่าธุรกิจมีความแตกต่าง
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ประกันชีวิตกลุ่มเอฟดับบลิวดี" anchor="" linktype="internal" class="" title="ดูผลิตภัณฑ์ประกันชีวิตกลุ่มเพื่อธุรกิจ"  querystring="" id="{0D08A74E-81B5-4DFD-9B53-B8AD7413F555}" />
