---
ID: "c97b30b8-a96b-4340-a3e7-b794159475bd"
Parent: "afd82d5f-c882-478a-8a19-b3c7706b2f7f"
Template: "784a15db-39f4-4022-a66b-813bc00279bd"
Path: "/sitecore/content/fwd/fwd-th/Components/masterfeaturefolder/product-features"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Features
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191112T114643Z
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200211T071427Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
