---
ID: "337107f6-6431-4012-a32b-537e7508820e"
Parent: "62160f68-a4c6-4786-a770-31de79383545"
Template: "69b601a8-8555-4411-8c17-aa91671eec32"
Path: /sitecore/templates/Branches/FWD/Foundation/Market Site Rollout/MultiMarketSiteRoot/$name/Content/Tags/commonTags/contentType/Product
DB: master
SharedFields:
- ID: "a903eb23-a8d6-4a9a-bd27-4bd363b1fcf0"
  Hint: searchName
  Value: Product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03834b49-81cd-4ea6-956b-1cf3018dcf8a"
      Hint: name
      Value: Product
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191101T172906Z
