/*9fbef606107a605d69c0edbcd8029e5d*/
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.Extensions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.Services")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.Extensions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.Services")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wffm", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Constants+RenderingAttribute.#Wffm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#GetMultiListValueItems(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Webffm", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.RenderingAttributes.#Webffm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#ImageLink(Sitecore.Data.Items.Item,Sitecore.Data.ID,Sitecore.Resources.Media.MediaUrlOptions)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#TargetItem(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#LinkFieldLink(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#LinkFieldOptions(Sitecore.Data.Items.Item,Sitecore.Data.ID,FWD.Foundation.SitecoreExtensions.Extensions.LinkFieldOption)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#FieldHasValue(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#GetInteger(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#GetMultiListValueItems(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Rules.ReplaceSpaceWithHyphen`1.#Apply(!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wffm", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.RenderingAttributes.#Wffm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.Rules")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.Rules")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.Extensions.ItemExtensions.#IsDerived(Sitecore.Data.Items.Item,Sitecore.Data.ID)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Fwd", Scope = "type", Target = "FWD.Foundation.SitecoreExtensions.Rules.HasFwdRootPath`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleImageUrl.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultiListComputedIndexAvailableColors.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultiListComputedIndexCargoVolume.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultiListComputedIndexTransmissionType.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleProductCategoryField.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multilist", Scope = "type", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultilistComputedIndexAvailableColors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultilistComputedIndexAvailableColors.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multilist", Scope = "type", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultilistComputedIndexCargoVolume")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultilistComputedIndexCargoVolume.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multilist", Scope = "type", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultilistComputedIndexTransmissionType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedIndex.SampleMultilistComputedIndexTransmissionType.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.GlobalConstants.#SitecoreShellPath")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields.SampleTransmissionType.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields.SampleProductCategoryField.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields.SampleImageUrl.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields.SampleCargoVolume.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields.SampleAvailableColors.#ComputeFieldValue(Sitecore.ContentSearch.IIndexable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FWD", Scope = "namespace", Target = "FWD.Foundation.SitecoreExtensions.ComputedFields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "member", Target = "FWD.Foundation.SitecoreExtensions.GlobalConstants.#Sitecore")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.Handlers.RobotsHandler.ProcessRequest(System.Web.HttpContext)")]// This file is used by Code Analysis to maintain SuppressMessage 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S4040:Strings should be normalized to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.Pipelines.CustomLanguageResolver.Process(Sitecore.Pipelines.HttpRequest.HttpRequestArgs)")]// attributes that are applied to this project.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S1541:Methods and properties should not be too complex", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.Pipelines.Handle404ErrorProcessor.Process(Sitecore.Pipelines.HttpRequest.HttpRequestArgs)")]// Project-level suppressions either have no target or are given 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.Pipelines.Handle404ErrorProcessor.Process(Sitecore.Pipelines.HttpRequest.HttpRequestArgs)")]// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S4040:Strings should be normalized to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.Rules.ReplaceSpaceWithHyphen`1.Apply(`0)")]//

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S1541:Methods and properties should not be too complex", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.Rules.ReplaceSpaceWithHyphen`1.Apply(`0)")]// To add a suppression to this file, right-click the message in the 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.ComputedFields.SampleAvailableColors.ComputeFieldValue(Sitecore.ContentSearch.IIndexable)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.ComputedFields.SampleCargoVolume.ComputeFieldValue(Sitecore.ContentSearch.IIndexable)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.ComputedFields.SampleImageUrl.ComputeFieldValue(Sitecore.ContentSearch.IIndexable)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.ComputedFields.SampleProductCategoryField.ComputeFieldValue(Sitecore.ContentSearch.IIndexable)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:FWD.Foundation.SitecoreExtensions.ComputedFields.SampleTransmissionType.ComputeFieldValue(Sitecore.ContentSearch.IIndexable)~System.Object")]// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.
