---
ID: "cd10f076-7da5-45bb-a91d-c435a5d2ca56"
Parent: "83082f20-c297-4f42-825e-01eddfb48929"
Template: "b5e7b47e-3ee9-4427-8737-f48ce39d600c"
Path: "/sitecore/content/fwd/fwd-th/Home/Testing/home-page/Support/premium-payment/local-folder/premium-payment/life-and-accident-insurance/Autopay/where-to-send-your-application-form"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Where to send your application form
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200107T090748Z
    - ID: "8a22f96c-782f-47ed-9e47-0416fc198a33"
      Hint: description
      Value: |
        <p><strong>Where to send your application form</strong></p>
        <p>FWD Life Insurance Public Company Limited, 130-132 Sindhorn Building Tower 3, 28th floor Withayu Road, Lumpini, Pathumwan, Bangkok 10330</p>
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T104948Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "8a22f96c-782f-47ed-9e47-0416fc198a33"
      Hint: description
      Value: |
        <p><strong>Where to send your application form</strong></p>
        <p>FWD Life Insurance Public Company Limited, 130-132 Sindhorn Building Tower 3, 28th floor Withayu Road, Lumpini, Pathumwan, Bangkok 10330</p>
