---
ID: "7ef68fd3-c87e-4e5f-9b9c-483934dfec17"
Parent: "b6a4a857-4afe-4885-b9c3-d3d6738e621a"
Template: "8bac8cc4-dec2-4c0c-9d84-6dfb7d398819"
Path: "/sitecore/content/fwd/fwd-th/Components/footerLinks/footer-navigation-links/column-1/Product"
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{BD9D2AB7-4AC1-454B-A6A8-53B1DC5C0AC4}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200227T102612Z
    - ID: "261f3e4a-43df-4750-aa16-8286a548f9db"
      Hint: link
      Value: |
        <link text="ผลิตภัณฑ์" anchor="" linktype="internal" class="" title=""  querystring="" id="{528D2C44-05E6-4E13-8C4C-0A7FFF35B120}" />
    - ID: "88cf131d-d600-4b97-a626-04cc28dc352e"
      Hint: title
      Value: Products
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200314T094101Z
    - ID: "261f3e4a-43df-4750-aa16-8286a548f9db"
      Hint: link
      Value: |
        <link text="ผลิตภัณฑ์" anchor="" linktype="internal" class="" title=""  querystring="" id="{528D2C44-05E6-4E13-8C4C-0A7FFF35B120}" />
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "88cf131d-d600-4b97-a626-04cc28dc352e"
      Hint: title
      Value: ผลิตภัณฑ์
