---
ID: "dfa795f4-b79b-43e2-a239-6a5fdbe44202"
Parent: "a04fbdb0-717e-4e89-8d93-92c705ee073a"
Template: "681b61a2-6f52-4119-b8f4-033587eaeacc"
Path: "/sitecore/content/fwd/fwd-th/Home/Testing/home-page/Products/primary-need/local-folder/ProductRelatedArticles"
DB: master
SharedFields:
- ID: "8f397566-a4d1-4f23-8594-dce13b3720fe"
  Hint: apiSortBy
  Value: "{C27171A2-8AC2-4005-8076-DC7489E3997B}"
- ID: "b2b3b585-1cdb-45db-bfd2-a40636d24817"
  Hint: apiContentType
  Value: "{3B19D2B5-AAA3-4FB7-A107-4CEC5F9110F1}"
- ID: "bd1fe0cc-270d-4276-a07d-da02b962d325"
  Hint: primaryNeedTags
  Type: Multilist
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200402T081758Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\testuser
    - ID: "d88ea793-1587-4f65-ae5c-80926cd5438b"
      Hint: subTitle
      Value: 
    - ID: "e276cbc0-53a7-497f-870a-0a505ab8195b"
      Hint: title
      Value: Your daily inspiration
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200413T073427Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "e276cbc0-53a7-497f-870a-0a505ab8195b"
      Hint: title
      Value: Your daily inspiration
