---
ID: "6ae30d48-1e23-4c99-ba4a-c339e3eab53f"
Parent: "57e19dc5-8b40-4da4-8d24-ba53098ea606"
Template: "ad6870d4-2dd6-40ef-a8fa-941ab32cee43"
Path: "/sitecore/content/fwd/fwd-th/Home/Support/Forms/local-folder/DropDownItem/Premium payment/Application to set up premium payments via a savings account for policies bought from SCB"
DB: master
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 0
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{BD9D2AB7-4AC1-454B-A6A8-53B1DC5C0AC4}"
- ID: "ff4d8f7a-06bf-45ab-8306-c9bf727c5bd9"
  Hint: buttonIcon
  Value: "{96BC3A53-AB72-49EF-BA31-37D901B59263}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200918T015414Z
    - ID: "27e6d694-274d-4a38-8800-12f8f9ec1ac4"
      Hint: title
      Value: Application to set up premium payments via a savings account for policies bought from SCB or through a former agency channel
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nuntarut
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{2EEA27C1-B29E-461B-A377-D38E0703A756}" />
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201001T081727Z
    - ID: "27e6d694-274d-4a38-8800-12f8f9ec1ac4"
      Hint: title
      Value: Application to set up premium payments via a savings account for policies bought from SCB or through a former agency channel
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nuntarut
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20201001T081727Z
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link linktype="media" target="" id="{2EEA27C1-B29E-461B-A377-D38E0703A756}" />
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200918T015403Z
    - ID: "27e6d694-274d-4a38-8800-12f8f9ec1ac4"
      Hint: title
      Value: หนังสือยินยอมให้หักบัญชีเงินฝาก (กรมธรรม์ที่ซื้อผ่านธนาคารไทยพาณิชย์หรือตัวแทนเดิม)
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nuntarut
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{2EEA27C1-B29E-461B-A377-D38E0703A756}" />
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200925T160545Z
    - ID: "27e6d694-274d-4a38-8800-12f8f9ec1ac4"
      Hint: title
      Value: หนังสือยินยอมให้หักบัญชีเงินฝาก (กรมธรรม์ที่ซื้อผ่านธนาคารไทยพาณิชย์หรือตัวแทนเดิม)
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nuntarut
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200925T160545Z
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{2EEA27C1-B29E-461B-A377-D38E0703A756}" />
  - Version: 3
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201001T081929Z
    - ID: "27e6d694-274d-4a38-8800-12f8f9ec1ac4"
      Hint: title
      Value: หนังสือยินยอมให้หักบัญชีเงินฝาก (กรมธรรม์ที่ซื้อผ่านธนาคารไทยพาณิชย์หรือตัวแทนเดิม)
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nuntarut
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20201001T081929Z
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link linktype="media" target="" id="{2EEA27C1-B29E-461B-A377-D38E0703A756}" />
