---
ID: "46efd563-0e58-4c65-a967-f1838d26aaf4"
Parent: "94dcacbe-4314-4464-ba5b-6b74cb22020d"
Template: "4faa2cd7-63df-4c30-abb2-9d55380d2106"
Path: "/sitecore/content/fwd/fwd-th/Components/headerLinks/header-navigation-links/business-insurance/Products"
DB: master
SharedFields:
- ID: "0506ee6d-80ab-42a9-aa0d-06cb556b05b0"
  Hint: pageType
  Value: "{186F12B8-F721-489F-8DF9-67D5F10C69D5}"
- ID: "a6ee811d-8f6f-4560-80b5-a4faa92bb6db"
  Hint: buttonIcon
  Value: "{19FCB2E6-0897-424F-9D15-B35209E646ED}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200312T184728Z
    - ID: "261f3e4a-43df-4750-aa16-8286a548f9db"
      Hint: link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{0D08A74E-81B5-4DFD-9B53-B8AD7413F555}" />
    - ID: "88cf131d-d600-4b97-a626-04cc28dc352e"
      Hint: title
      Value: Products
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200316T190612Z
    - ID: "261f3e4a-43df-4750-aa16-8286a548f9db"
      Hint: link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{0D08A74E-81B5-4DFD-9B53-B8AD7413F555}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "88cf131d-d600-4b97-a626-04cc28dc352e"
      Hint: title
      Value: ผลิตภัณฑ์
