---
ID: "d45ff3fe-f67f-46b0-9396-cc1061052343"
Parent: "e8495357-264a-4aca-b8db-798d8bcf06e2"
Template: "681b61a2-6f52-4119-b8f4-033587eaeacc"
Path: "/sitecore/content/fwd/fwd-th/Home/Testing/home-page/Products/Health/CancerFighterRider/local-folder/Product Related Articles"
DB: master
SharedFields:
- ID: "b2b3b585-1cdb-45db-bfd2-a40636d24817"
  Hint: apiContentType
  Value: "{20162863-AE86-4B42-9AEC-B7A81A345553}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200826T075949Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d88ea793-1587-4f65-ae5c-80926cd5438b"
      Hint: subTitle
      Value: 
    - ID: "e276cbc0-53a7-497f-870a-0a505ab8195b"
      Hint: title
      Value: Your daily inspiration
