---
ID: "96d58d84-50c3-462b-b495-2d7424a1c977"
Parent: "81d2ab2b-e499-4139-a157-3100532ef71d"
Template: "8bac8cc4-dec2-4c0c-9d84-6dfb7d398819"
Path: "/sitecore/content/fwd/fwd-th/Components/sitemapLinks/category-section/business-insurance-section/column-1/Product"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200227T102612Z
    - ID: "261f3e4a-43df-4750-aa16-8286a548f9db"
      Hint: link
      Value: |
        <link text="Products" anchor="" linktype="internal" class="" title=""  querystring="" id="{0D08A74E-81B5-4DFD-9B53-B8AD7413F555}" />
    - ID: "88cf131d-d600-4b97-a626-04cc28dc352e"
      Hint: title
      Value: Products
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200314T094059Z
    - ID: "261f3e4a-43df-4750-aa16-8286a548f9db"
      Hint: link
      Value: |
        <link text="Products" anchor="" linktype="internal" class="" title=""  querystring="" id="{0D08A74E-81B5-4DFD-9B53-B8AD7413F555}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "88cf131d-d600-4b97-a626-04cc28dc352e"
      Hint: title
      Value: ผลิตภัณฑ์
