---
ID: "9ba2f0e0-318c-4e18-a616-12f2cf02aec4"
Parent: "7bba63c2-c4b1-416b-8f72-a7b981d3d1ba"
Template: "51555475-5028-4b05-9b45-53be53615704"
Path: "/sitecore/content/fwd/fwd-th/Home/Products/Health/critical-illness/local-folder/Product brochure"
DB: master
SharedFields:
- ID: "61cf7151-0cbd-4db4-9738-d753a55a6e65"
  Hint: __Enforce version presence
  Type: Checkbox
  Value: 0
- ID: "6cd9b2c8-a41a-439e-8166-b0b7b0086f49"
  Hint: buttonMode
  Value: "{2D7E3979-8DAE-42D1-BFDF-45522DB9A1B9}"
- ID: "9cb76228-fc26-48b7-bd66-1c6e133b625d"
  Hint: secondaryLinkButtonMode
  Value: 
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{BD9D2AB7-4AC1-454B-A6A8-53B1DC5C0AC4}"
- ID: "dab4200c-a87f-4605-b2f7-2544616ece6e"
  Hint: secondaryLinkButtonIcon
  Value: 
- ID: "ff4d8f7a-06bf-45ab-8306-c9bf727c5bd9"
  Hint: buttonIcon
  Value: "{96BC3A53-AB72-49EF-BA31-37D901B59263}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "080cac52-a76d-44ce-a9e6-6d60dc56ad03"
      Hint: subTitle
      Value: 
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191205T121735Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: <span>Get our official product brochure for personal use or share it with friends and family</span><span>.</span>
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: Product brochure
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="Download brochure" linktype="external" url="" anchor="" target="" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: 
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "080cac52-a76d-44ce-a9e6-6d60dc56ad03"
      Hint: subTitle
      Value: 
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T055202Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: <span>รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว</span>
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{4752D0CD-6164-499C-B076-9AEAF8306FC2}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
  - Version: 2
    Fields:
    - ID: "080cac52-a76d-44ce-a9e6-6d60dc56ad03"
      Hint: subTitle
      Value: 
    - ID: "1e38642e-dc23-498d-95c1-c8cce55eeed5"
      Hint: mobileImage
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200930T101833Z
    - ID: "2ff96014-55f5-468f-9a29-640ece5a9cea"
      Hint: image
      Value: 
    - ID: "3aa2547f-a64b-4ac7-81e4-9bd06adff03d"
      Hint: description
      Value: <span>รับโบร์ชัวร์ผลิตภัณฑ์ สำหรับใช้ในการพิจารณาส่วนตัว หรือแบ่งปันให้กับเพื่อนและครอบครัว</span>
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{3302EB81-28CF-4EDF-B3F4-A175A8EEC671}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Hein
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200930T101833Z
    - ID: "d8e6a378-12df-4f47-903b-b691f8217f29"
      Hint: title
      Value: โบรชัวร์ผลิตภัณฑ์
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: |
        <link text="ดาวน์โหลดโบรชัวร์" linktype="media" target="" id="{40931F99-F477-43B5-8166-CF73B3BD4CDD}" />
    - ID: "f365b9cc-c804-4520-8a22-6c165b97cfda"
      Hint: mediaType
      Value: "{A537F571-3E6F-4CDD-A9F9-5093569C9C19}"
