---
ID: "131f2aba-62ad-4e77-bc04-a3482760ef74"
Parent: "cd66d9c9-56e0-4c8f-a975-8b090b875ff2"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/FWD/Feature/Global/PowerShell/_powerShellModulesSetting/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200516T093454Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
