---
ID: "7e44c699-57cd-46cf-97ec-1ebd9c84a869"
Parent: "52f90b08-b003-41d1-a228-3d810eb9a2fe"
Template: "0b8ac58e-2d57-4ecd-bcdf-2cebaaa0c8b7"
Path: "/sitecore/content/fwd/fwd-th/Content/product-category/Product"
DB: master
SharedFields:
- ID: "1d7292b5-07c1-4268-b196-263841c6000a"
  Hint: key
  Value: product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191111T042717Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "fe6b1114-8ec9-4afa-a14b-cdc2f1004ab8"
      Hint: value
      Value: Product
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200211T064826Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "fe6b1114-8ec9-4afa-a14b-cdc2f1004ab8"
      Hint: value
      Value: ผลิตภัณฑ์
