---
ID: "b22424bf-0085-43fd-bedb-fec79252531e"
Parent: "2b93e66c-a0bb-4e6c-bfae-a12d0e197e33"
Template: "267d9ac7-5d85-4e9d-af89-99ab296cc218"
Path: "/sitecore/content/fwd/fwd-th/fwd-th-app-Dictionary/Labels/Product"
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200710T094626Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200824T093002Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{D80D2A5C-D5F8-4DA1-8828-B4F51D64461B}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
