---
ID: "1ed03fc0-c4d9-4107-9fa2-a70adc2a62f0"
Parent: "113fec0c-03df-4265-a203-6f409bf8897b"
Template: "681b61a2-6f52-4119-b8f4-033587eaeacc"
Path: "/sitecore/content/fwd/fwd-th/Home/Testing/home-page/branding-pages/New Product Page/flexi-eb/local-folder/Product Related Articles"
DB: master
SharedFields:
- ID: "2250f909-bae3-415f-a645-9d07826b6566"
  Hint: apiPageSize
  Value: 2
- ID: "8f397566-a4d1-4f23-8594-dce13b3720fe"
  Hint: apiSortBy
  Value: 
- ID: "b2b3b585-1cdb-45db-bfd2-a40636d24817"
  Hint: apiContentType
  Value: "{3B19D2B5-AAA3-4FB7-A107-4CEC5F9110F1}"
- ID: "ef2bcb82-b8a8-4be6-88a7-5269b777ad1d"
  Hint: apiSubType
  Value: "{2B21E021-7F9E-4586-B882-6AD8C2C0FEE3}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200121T120651Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d88ea793-1587-4f65-ae5c-80926cd5438b"
      Hint: subTitle
      Value: Your daily inspiration
    - ID: "e276cbc0-53a7-497f-870a-0a505ab8195b"
      Hint: title
      Value: Your daily inspiration
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200129T115850Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "d88ea793-1587-4f65-ae5c-80926cd5438b"
      Hint: subTitle
      Value: Your daily inspiration
    - ID: "e276cbc0-53a7-497f-870a-0a505ab8195b"
      Hint: title
      Value: Your daily inspiration
