---
ID: "191452df-b680-4bb9-9c54-82886c721a02"
Parent: "264e278b-19f3-438f-9a1e-1964d78703fa"
Template: "7cd51b29-32c8-44bd-9afc-a2d5587d611c"
Path: "/sitecore/content/fwd/fwd-th/Home/Support/Forms/Hospital/local-folder/DropDownItem/Application"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Health care service for hospital
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200517T023440Z
    - ID: "2f5a22b8-fc21-4f5e-9046-64bc79c4ae0c"
      Hint: title
      Value: Health care services for hospitals
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joseph
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200517T023646Z
    - ID: "2f5a22b8-fc21-4f5e-9046-64bc79c4ae0c"
      Hint: title
      Value: บริการดูแลสุขภาพสำหรับโรงพยาบาล
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joseph
