---
ID: "c2ecbc98-98d9-4357-9146-9e1fee024bd1"
Parent: "d77061f0-4033-4e10-846d-b391b5a4d07d"
Template: "52873596-fd74-488b-9e6e-6382b1cc2eb2"
Path: "/sitecore/content/fwd/fwd-th/Home/Testing/home-page/Products"
DB: master
SharedFields:
- ID: "1ba7a30d-5523-4af2-81f2-9e432cd805cd"
  Hint: contentType
  Value: "{A57B5556-98B3-4112-AC9F-1926D90455B8}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{0E51C73B-3192-4E96-AA09-4F095CD69D08}"
          s:ds="{CCCFE6F7-1169-409A-AB37-3CAE30D24488}" />
        <r
          uid="{A20F77A7-562E-4E3A-B76A-3FA65C15B57C}">
          <p:d />
        </r>
        <r
          uid="{E0B1D925-F5BE-47D6-B73A-ADEE19477395}">
          <p:d />
        </r>
        <r
          uid="{BD9BBFD0-CC3F-422C-AC56-008CBA8FCADE}"
          p:after="r[@uid='{0E51C73B-3192-4E96-AA09-4F095CD69D08}']"
          s:ds="{CD8EB3EA-852C-4253-9D6D-48A4B21D0E84}"
          s:id="{BC225970-9A8C-4F64-BEF1-B09D71ACB5CC}"
          s:par=""
          s:ph="jss-main" />
        <r
          uid="{3A057B8B-329A-429B-A477-DBE835FB6E15}"
          p:after="r[@uid='{BD9BBFD0-CC3F-422C-AC56-008CBA8FCADE}']"
          s:ds="{81C04A12-D44C-4DE7-A64F-36AF067411CD}"
          s:id="{9714408E-904A-4275-84C6-DACC99E42B9D}"
          s:par=""
          s:ph="jss-main" />
        <r
          uid="{57B90644-83E2-4CC2-BFE0-0E2033A7B13E}"
          s:ph="jss-main-1" />
        <r
          uid="{9FA7C353-70D2-4A2F-ABB2-51FD78BB237B}"
          p:after="r[@uid='{57B90644-83E2-4CC2-BFE0-0E2033A7B13E}']"
          s:ds="{8DFC565D-0A54-4DDD-8BBC-6FB96C29FCD3}"
          s:id="{E9189BB0-4352-4FC7-B5F6-7C992E35E897}"
          s:par="paddingBottom=%7b0EF687F9-57C6-4122-B17E-DFBCF0A0BAEA%7d&amp;paddingTop=%7b0EF687F9-57C6-4122-B17E-DFBCF0A0BAEA%7d&amp;anchorText&amp;backgroundColor=%7bEBDF491B-A72E-47CA-A391-E44A39C9C329%7d&amp;buttonAlignment=%7bCF02F396-DAFD-448E-BC19-15E66C7CBA54%7d&amp;variant&amp;divider"
          s:ph="jss-main" />
        <r
          uid="{E04C4397-F80D-4FD9-8C84-AA35987EA0C7}"
          p:after="*[1=2]"
          s:ds="{882A58F8-DDD7-4BA9-8EFC-D8D561AEC4F1}"
          s:par="anchorText&amp;divider&amp;backgroundColor=%7bF6BA8583-13B7-4FC7-A1D4-FC8F11DCE6B1%7d&amp;paddingTop=%7b39A5175B-32BA-4968-842E-ABFC2410ABFF%7d&amp;paddingBottom=%7bDE1D2D2E-FDFA-4E0D-A649-E38F3822F767%7d" />
      </d>
    </r>
- ID: "ff451472-1b55-4228-b14d-ab9b2a449792"
  Hint: isPageSearchable
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Get Insured
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{3A057B8B-329A-429B-A477-DBE835FB6E15}">
              <p:d />
            </r>
            <r
              uid="{384E8665-832B-428F-AB1C-3B31586C5319}"
              p:after="r[@uid='{BD9BBFD0-CC3F-422C-AC56-008CBA8FCADE}']"
              s:ds="{81C04A12-D44C-4DE7-A64F-36AF067411CD}"
              s:id="{9714408E-904A-4275-84C6-DACC99E42B9D}"
              s:ph="jss-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191104T102704Z
    - ID: "7d76900d-2ec8-4b47-81fc-2baf505287be"
      Hint: metadataTitle
      Value: Product Landing
- Language: th
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Get Insured
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{3A057B8B-329A-429B-A477-DBE835FB6E15}">
              <p:d />
            </r>
            <r
              uid="{6739198D-8B88-49C3-AC41-77833664F303}"
              p:after="r[@uid='{BD9BBFD0-CC3F-422C-AC56-008CBA8FCADE}']"
              s:ds="{81C04A12-D44C-4DE7-A64F-36AF067411CD}"
              s:id="{9714408E-904A-4275-84C6-DACC99E42B9D}"
              s:ph="jss-main" />
            <r
              uid="{57B90644-83E2-4CC2-BFE0-0E2033A7B13E}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200115T054158Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "7d76900d-2ec8-4b47-81fc-2baf505287be"
      Hint: metadataTitle
      Value: Product Landing Thai
