---
ID: "d16fd8d9-564a-4ddb-a096-a87d6809ea31"
Parent: "a332dade-4d9d-40c4-b31d-f2ed1badde18"
Template: "967a8dad-4a23-491b-95e2-295dec0b64b3"
Path: "/sitecore/content/fwd/fwd-th/Home/Testing/home-page/Privileges/Privilege2/local-folder/product-link-meta-data"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Link Meta Data
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191018T095324Z
    - ID: "ef4ceecf-b302-475f-be16-370851260a17"
      Hint: title
      Value: You might be interested in
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200311T094133Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "ef4ceecf-b302-475f-be16-370851260a17"
      Hint: title
      Value: You might be interested in
