---
ID: "d2b414ad-f35c-4474-a74c-9b8258a059d7"
Parent: "b557babc-65d4-43f0-baf7-f71a64bd6508"
Template: "8d254d4a-bd30-4b07-8fa0-7464260d4bbc"
Path: /sitecore/templates/Branches/FWD/Foundation/Market Site Rollout/MultiMarketSiteRoot/$name/Content/Tags/productsTags
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Products Tags
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191101T165020Z
