---
ID: "b146f3fa-1af8-49fa-b8f3-be42a749bd9d"
Parent: "ffaa0a82-fa41-4f50-a7c4-c2c668ded9b5"
Template: "b4c08e6e-4910-4cf1-8357-5135729afafb"
Path: "/sitecore/templates/Branches/FWD/Foundation/Market Site Rollout/MultiMarketSiteRoot/$name/Home/About Us/local-folder/product-link-2"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Link 2
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191018T093744Z
    - ID: "9466c25e-e97e-4373-91c3-e648a98ea63e"
      Hint: title
      Value: Unlimited flexibility and support for groups and businesses
    - ID: "9aef0a70-2235-4e84-9854-1e4597e6c385"
      Hint: subTitle
      Value: "Our group insurance are designed to adapt in unique setting and requirement,complete with 24-hour support.Our group insurance are designed to adapt in unique setting and requirement,complete with 24-hour support"
    - ID: "eeba35bc-d87b-44d7-bf8e-bd33cf543ac8"
      Hint: link
      Value: 
