---
ID: "136aa02c-41c6-4e79-88e1-7893b161a37f"
Parent: "648fb00d-66f4-49ce-b707-3ef5be529dbe"
Template: "d48ab251-45a3-498a-a8c1-629e33a6b9b4"
Path: "/sitecore/content/fwd/fwd-th/Home/FormsList/product-enquiry-form"
DB: master
SharedFields:
- ID: "97b969dc-df88-4451-baad-f8101a25d27c"
  Hint: formEmailTemplate
  Value: |
    <link text="" linktype="form" querystring="" target="" id="{21FBB3BF-9570-435B-986D-3E00CB9CFAA4}" />
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <p
          uid="{D14661AB-7F89-4E68-A125-FBBB88BFB7B6}">
          <p:d />
        </p>
        <r
          uid="{101A42A4-309F-49A5-BEDA-8C1D9298BF8D}"
          s:ds="{529EA3C6-D040-41BB-A820-FDAEEA3288D9}"
          s:id="{D12A5E12-4AB2-4330-8D72-77EA8D372515}"
          s:par="formType=conversational"
          s:ph="jss-main" />
        <r
          uid="{9E687E41-FA14-4810-A780-5B42B5322AE8}">
          <p:d />
        </r>
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Enquiry Form
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191126T040213Z
    - ID: "51d4b1ca-977d-48d7-a102-b29f5018079d"
      Hint: apiList
      Type: Multilist
      Value: "{D58E3660-0AB7-4811-AD6F-D007E52AF349}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: th
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T103624Z
    - ID: "51d4b1ca-977d-48d7-a102-b29f5018079d"
      Hint: apiList
      Type: Multilist
      Value: "{D58E3660-0AB7-4811-AD6F-D007E52AF349}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
